### PR TITLE
Hearply added and implemented to let certain commands be in the room …

### PR DESCRIPTION
**Pull request by jasonrhodes**
…or in DM

No idea how to test this shit except push it and watch it burn cool

### CODE REVIEW

**Comment by max-mathieu** [comment]
To test, you need to clone the cah-bot repo too
And then, either change the tag in package.json or replace the folder by a symlink to the hubot-cah folder to point to your version
Then, you run `bin/hubot` from the cah-bot folder and you can test (bin/hubot runs npm install)

**Comment by max-mathieu** [comment]
Fwiw, with your changes it seems like it cannot load the script anymore

**Comment by jasonrhodes** [comment]
Is that a problem

**Comment by jasonrhodes** [comment]
Turns out `robot.reply` -- not a thing! It's `robot.respond`, so after adjusting accordingly, this works.

Also: the error messages I got for this were shit-tastic.

**Pull request merged**
